#!/bin/bash
export DISPLAY=:8
#export LD_PRELOAD=/usr/lib32/libglc-hook.so
glc-capture -o /dolan/osurecord/glc/%pid%.glc --compressed=300 --uncompressed=300 --unscaled=300 --audio-skip --pbo --compression=none --lock-fps -f 60 -b back -s sudo -u osu LD_PRELOAD=/usr/lib32/libglc-hook.so GLC_START=1 wine /home/osu/osu/osu\!.exe Replays/replay.osr
